const assert=require('node:assert/strict');
const fs=require('fs'),os=require('os'),path=require('path');
const DetectiveGame=require('../src/games/detective');
const CaseValidator=require('../src/games/detective/CaseValidator');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'wind-detective-'));
const game=new DetectiveGame({dataDir:dir,timeZone:'Asia/Ho_Chi_Minh'});
const a=game.getDailyCase('guild-test',new Date('2026-09-24T00:00:00Z'));
const b=game.getDailyCase('guild-test',new Date('2026-09-24T16:59:00Z'));
const c=game.getDailyCase('guild-test',new Date('2026-09-24T17:01:00Z'));
assert.equal(a.id,b.id);
assert.notEqual(a.id,c.id);
assert.equal(new CaseValidator().validate(a).valid,true);
const user='user-test';
game.startInvestigation(user,a);
for(const t of a.investigationTargets.slice(0,4))game.investigate(user,a,t.id);
game.interrogate(user,a,a.suspects[0].id,'time');
for(const id of ['T2','T3','T4'])game.addTimelineEvent(user,a,id);
const result=game.submit(user,a,{culprit:a.solution.culpritName,motive:a.solution.motive,timeline:['T2','T3','T4'],reasoning:'camera time key'});
assert.ok(result.result.total>0);
assert.equal(result.profile.casesSolved,1);
assert.equal(result.profile.streak,1);
console.log('Discord Detective tests passed.');
