const {SlashCommandBuilder,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,ModalBuilder,TextInputBuilder,TextInputStyle,MessageFlags}=require('discord.js');
const DetectiveGame=require('../games/detective');
const game=new DetectiveGame();
const commandsData=[new SlashCommandBuilder().setName('detective').setDescription('🕵️ Discord Detective').addSubcommand(s=>s.setName('case').setDescription('Xem Daily Case')).addSubcommand(s=>s.setName('join').setDescription('Tham gia điều tra chung')).addSubcommand(s=>s.setName('dossier').setDescription('Xem hồ sơ điều tra chung')).addSubcommand(s=>s.setName('hypothesis').setDescription('Ghi giả thuyết điều tra').addStringOption(o=>o.setName('text').setDescription('Giả thuyết của bạn').setRequired(true).setMaxLength(1000))).addSubcommand(s=>s.setName('profile').setDescription('Xem hồ sơ').addUserOption(o=>o.setName('user').setDescription('Người muốn xem hồ sơ'))).addSubcommand(s=>s.setName('leaderboard').setDescription('Bảng xếp hạng').addIntegerOption(o=>o.setName('limit').setDescription('Số người').setMinValue(1).setMaxValue(10))).toJSON()];

async function handleDetectiveInteraction(i){
  const cmd=i.isChatInputCommand()&&i.commandName==='detective', comp=(i.isButton()||i.isStringSelectMenu()||i.isModalSubmit())&&String(i.customId||'').startsWith('detective:');
  if(!cmd&&!comp)return false;if(!i.guildId){await reply(i,{content:'❌ Chỉ hoạt động trong server.',flags:MessageFlags.Ephemeral});return true;}
  try{
    if(cmd){const s=i.options.getSubcommand();if(s==='case')return await showCase(i);if(s==='join')return await joinCase(i);if(s==='dossier')return await dossier(i);if(s==='hypothesis')return await hypothesis(i,i.options.getString('text'));if(s==='profile')return await profile(i,i.options.getUser('user')||i.user);return await leaderboard(i,i.options.getInteger('limit')||10);}
    const p=String(i.customId).split(':'),caseId=p[2];
    if(!caseId)return reply(i,{content:'Tương tác vụ án đã hết hạn. Hãy mở lại /detective case.',flags:MessageFlags.Ephemeral});
    if(p[1]==='investigate')return await investigateMenu(i,caseId);if(p[1]==='inspect')return await inspect(i,i.values?.[0],caseId);if(p[1]==='suspects')return await suspects(i,caseId);if(p[1]==='questions')return await questions(i,i.values?.[0],caseId);if(p[1]==='questions_action')return await interrogate(i,p[3],i.values?.[0],caseId);if(p[1]==='timeline')return await timeline(i,caseId);if(p[1]==='timeline_menu')return await addTimeline(i,i.values?.[0],caseId);if(p[1]==='submit')return await submitModal(i,caseId);if(i.isModalSubmit()&&p[1]==='submit_modal')return await submitReport(i,caseId);
    return false;
  }catch(e){await reply(i,{content:'⚠️ Detective: '+e.message,flags:MessageFlags.Ephemeral});return true;}
}
function caseData(i,caseId){const c=caseId?game.getCaseById(i.guildId,caseId):game.getDailyCase(i.guildId);if(!c)throw new Error('Không tìm thấy vụ án này trong server.');return c;}
async function showCase(i){const c=caseData(i),session=game.joinSession(i.guildId,c,i.user.id),id=c.id;const rows=[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('detective:investigate:'+id).setLabel('🔎 Điều tra').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('detective:suspects:'+id).setLabel('👥 Nghi phạm').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('detective:timeline:'+id).setLabel('🕐 Timeline').setStyle(ButtonStyle.Secondary)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('detective:submit:'+id).setLabel('⚖️ Nộp kết luận').setStyle(ButtonStyle.Success))];return i.reply({embeds:[new EmbedBuilder().setTitle('🕵️ DAILY CASE — '+c.title).setDescription(c.summary).addFields({name:'📊 Difficulty',value:'⭐'.repeat(c.difficulty),inline:true},{name:'🔎 Evidence',value:session.discoveredEvidence.length+'/'+c.evidence.length,inline:true},{name:'👥 Investigators',value:String(session.players.length),inline:true},{name:'👥 Suspects',value:c.suspects.map(s=>s.id+' — '+s.name).join('\n')}),],components:rows});}
async function joinCase(i){const current=game.joinDailySession(i.guildId,i.user.id);if(!current)return reply(i,{content:'Không có phiên điều tra đang hoạt động hôm nay. Dùng /detective case để bắt đầu.',flags:MessageFlags.Ephemeral});const {session}=current;return i.reply({embeds:[new EmbedBuilder().setTitle('INVESTIGATION SESSION').addFields({name:'Investigators',value:String(session.players.length),inline:true},{name:'Shared discoveries',value:String(session.discoveredEvidence.length),inline:true},{name:'Hypotheses',value:String(session.hypotheses.length),inline:true}).setDescription('Bạn đã tham gia phiên điều tra chung. Dùng /detective dossier để xem hồ sơ.')],flags:MessageFlags.Ephemeral});}
async function investigateMenu(i,caseId){const c=caseData(i,caseId),session=game.joinSession(i.guildId,c,i.user.id),targets=c.investigationTargets.filter(t=>!session.inspectedTargets.includes(t.id));if(!targets.length)return reply(i,{content:'🔎 Đội điều tra đã kiểm tra hết địa điểm.',flags:MessageFlags.Ephemeral});const menu=new StringSelectMenuBuilder().setCustomId('detective:inspect:'+c.id).setPlaceholder('Chọn khu vực').addOptions(targets.map(t=>({label:t.label,value:t.id,description:'Tìm evidence'})));return i.reply({content:'🔎 Chọn khu vực để điều tra.',components:[new ActionRowBuilder().addComponents(menu)],flags:MessageFlags.Ephemeral});}
async function inspect(i,id,caseId){const c=caseData(i,caseId),r=game.investigateSession(i.guildId,i.user.id,c,id);if(r.completed)return reply(i,{content:'✅ Vụ án đã được kết luận.',flags:MessageFlags.Ephemeral});return i.update({content:(r.found?'🆕 Discovery shared with the team\n':'📁 Đội đã ghi nhận vật chứng này.\n')+(r.evidence.tags.includes('red_herring')?'🟡 Chi tiết cần kiểm chứng':'🟢 Vật chứng')+'\n\n**'+r.evidence.name+'**\n'+r.evidence.description,components:[]});}
async function suspects(i,caseId){const c=caseData(i,caseId),menu=new StringSelectMenuBuilder().setCustomId('detective:questions:'+c.id).setPlaceholder('Chọn nghi phạm').addOptions(c.suspects.map(s=>({label:s.id+' — '+s.name,value:s.id,description:'Thẩm vấn'})));return i.reply({embeds:[new EmbedBuilder().setTitle('👥 Nghi phạm').setDescription(c.suspects.map(s=>s.id+' — '+s.name).join('\n'))],components:[new ActionRowBuilder().addComponents(menu)],flags:MessageFlags.Ephemeral});}
async function questions(i,id,caseId){const c=caseData(i,caseId),s=c.suspects.find(x=>x.id===id);if(!s)throw new Error('Không tìm thấy nghi phạm.');const menu=new StringSelectMenuBuilder().setCustomId('detective:questions_action:'+c.id+':'+id).setPlaceholder('Chọn câu hỏi').addOptions([{label:'Hỏi về thời gian',value:'time',description:'Kiểm tra alibi'},{label:'Hỏi về món đồ',value:'object',description:'Kiểm tra khả năng tiếp cận'},{label:'Hỏi về người khác',value:'person',description:'Tìm mâu thuẫn'}]);return i.update({content:'👤 '+s.name+' — chọn câu hỏi',components:[new ActionRowBuilder().addComponents(menu)]});}
async function interrogate(i,id,a,caseId){const c=caseData(i,caseId),r=game.interrogateSession(i.guildId,i.user.id,c,id,a);if(r.completed)return reply(i,{content:'✅ Vụ án đã được kết luận.',flags:MessageFlags.Ephemeral});return i.update({content:'👤 **Lời khai chung**\n\n'+r.response,components:[]});}
async function timeline(i,caseId){const c=caseData(i,caseId),menu=new StringSelectMenuBuilder().setCustomId('detective:timeline_menu:'+c.id).setPlaceholder('Chọn mốc').addOptions(c.timeline.map(t=>({label:t.time+' — '+t.id,value:t.id,description:t.text})));return i.reply({content:'🕐 Chọn mốc timeline.',components:[new ActionRowBuilder().addComponents(menu)],flags:MessageFlags.Ephemeral});}
async function addTimeline(i,id,caseId){const c=caseData(i,caseId);game.addSessionTimeline(i.guildId,i.user.id,c,id);return i.update({content:'🕐 Đã thêm '+id+' vào timeline chung.',components:[]});}
async function submitModal(i,caseId){const c=caseData(i,caseId),session=game.joinSession(i.guildId,c,i.user.id);if(session.discoveredEvidence.length<4||session.interrogatedSuspects.length<1)return reply(i,{content:'🔒 Đội cần ít nhất 4 vật chứng và 1 lần thẩm vấn.',flags:MessageFlags.Ephemeral});const m=new ModalBuilder().setCustomId('detective:submit_modal:'+c.id).setTitle('⚖️ Final Detective Report');for(const [id,label,ph,max] of [['culprit','Thủ phạm','S1 hoặc tên',100],['motive','Động cơ','Bạn nghĩ vì sao?',300],['timeline','Timeline','T2,T3,T4',100],['reconstruction','Tái dựng','Mốc, cơ chế, false lead, evidence',800],['reasoning','Lập luận','Giải thích kết luận',1000]])m.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(id).setLabel(label).setPlaceholder(ph).setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(max)));return i.showModal(m);}
async function submitReport(i,caseId){const c=caseData(i,caseId),r=game.submitSession(i.guildId,i.user.id,c,{culprit:i.fields.getTextInputValue('culprit'),motive:i.fields.getTextInputValue('motive'),timeline:i.fields.getTextInputValue('timeline').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean),reconstruction:i.fields.getTextInputValue('reconstruction'),reasoning:i.fields.getTextInputValue('reasoning')});return i.reply({embeds:[new EmbedBuilder().setTitle(r.result.culprit?'✅ Case Solved':'❌ Case Not Solved').setDescription('Thủ phạm: **'+c.solution.culpritName+'**\nĐiểm đội: **'+r.result.total+'**\nXP mỗi điều tra viên: **+'+r.result.xp+'**\nCulprit: '+(r.result.culprit?'✅':'❌')+' · Motive: '+(r.result.motive?'✅':'❌')+'\nTimeline: '+r.result.timelineScore+'/200 · Evidence: '+r.result.foundRequired+'/'+r.result.requiredEvidence+' · Reconstruction: '+(r.result.reconstructionScore||0)+'/300 · Reasoning: '+r.result.reasoningScore+'/500').addFields({name:'👥 Đội',value:String(r.session.players.length)+' điều tra viên'})],flags:MessageFlags.Ephemeral});}
async function dossier(i){const current=game.getDailySession(i.guildId);if(!current)return reply(i,{content:'Không có hồ sơ điều tra đang hoạt động hôm nay.',flags:MessageFlags.Ephemeral});const {caseData:c,session:s}=current,investigators=s.players.slice(0,20).map(p=>'<@'+p.userId+'>').join(', ')+(s.players.length>20?' và '+(s.players.length-20)+' người khác':'');const embed=new EmbedBuilder().setTitle('📁 Case Dossier — '+c.title).setDescription('Investigators: '+investigators+'\nStatus: '+s.status);const knownEvidence=s.discoveredEvidence.map(id=>c.evidence.find(item=>item.id===id)).filter(Boolean);embed.addFields({name:'DISCOVERED CLUES',value:knownEvidence.length?knownEvidence.map(item=>'**'+item.id+' · '+item.name+'**').join('\n').slice(0,1024):'Chưa có vật chứng được ghi nhận.'},{name:'CONTRADICTIONS',value:s.discoveredContradictions.length?s.discoveredContradictions.map(id=>{const item=c.caseModel?.contradictions?.find(entry=>entry.id===id);if(!item)return 'Mâu thuẫn đã ghi nhận.';const suspect=c.suspects.find(entry=>entry.id===item.suspectId);const evidence=c.evidence.find(entry=>entry.id===item.evidenceId);return (suspect?.name||'Nhân chứng')+' — lời khai cần đối chiếu với '+(evidence?.name||'vật chứng');}).join('\n').slice(0,1024):'Chưa xác lập mâu thuẫn.'},{name:'TIMELINE',value:s.timelineNotes.length?s.timelineNotes.map(id=>{const item=c.timeline.find(entry=>entry.id===id);return item?item.time+' — '+item.text:'';}).filter(Boolean).join('\n').slice(0,1024):'Chưa ghim mốc thời gian.'},{name:'THEORIES',value:s.hypotheses.length?s.hypotheses.slice(-5).map(item=>'<@'+item.playerId+'>: '+item.text).join('\n').slice(0,1024):'Chưa có giả thuyết.'});return i.reply({embeds:[embed],flags:MessageFlags.Ephemeral});}
async function hypothesis(i,text){const current=game.getDailySession(i.guildId);if(!current)return reply(i,{content:'Không có phiên điều tra đang hoạt động hôm nay.',flags:MessageFlags.Ephemeral});const result=game.addHypothesis(i.guildId,i.user.id,current.caseData,text);return i.reply({content:'🧠 Đã thêm giả thuyết '+result.hypothesis.id+' vào dossier chung.',flags:MessageFlags.Ephemeral});}
async function profile(i,u){const p=game.getProfile(u.id);return i.reply({embeds:[new EmbedBuilder().setTitle('🕵️ Detective Profile — '+u.username).addFields({name:'Rank',value:p.rank,inline:true},{name:'XP',value:String(p.xp),inline:true},{name:'Streak',value:'🔥 '+p.streak,inline:true},{name:'Cases',value:String(p.casesSolved),inline:true})],flags:MessageFlags.Ephemeral});}
async function leaderboard(i,n){const list=game.getLeaderboard(n);return i.reply({embeds:[new EmbedBuilder().setTitle('🏆 Detective Leaderboard').setDescription(list.length?list.map((p,x)=>'**'+(x+1)+'.** '+p.userId+' — '+p.xp+' XP · '+p.rank).join('\n'):'Chưa có Detective nào.')],flags:MessageFlags.Ephemeral});}
async function reply(i,p){return i.replied||i.deferred?i.followUp(p):i.reply(p);}
module.exports={commandsData,handleDetectiveInteraction,detectiveGame:game};