const {SlashCommandBuilder,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,ModalBuilder,TextInputBuilder,TextInputStyle,MessageFlags}=require('discord.js');
const DetectiveGame=require('../games/detective');
const game=new DetectiveGame();
const commandsData=[new SlashCommandBuilder().setName('detective').setDescription('🕵️ Discord Detective').addSubcommand(s=>s.setName('case').setDescription('Xem Daily Case')).addSubcommand(s=>s.setName('profile').setDescription('Xem hồ sơ').addUserOption(o=>o.setName('user').setDescription('Người muốn xem hồ sơ'))).addSubcommand(s=>s.setName('leaderboard').setDescription('Bảng xếp hạng').addIntegerOption(o=>o.setName('limit').setDescription('Số người').setMinValue(1).setMaxValue(10))).toJSON()];

async function handleDetectiveInteraction(i){
  const cmd=i.isChatInputCommand()&&i.commandName==='detective', comp=(i.isButton()||i.isStringSelectMenu()||i.isModalSubmit())&&String(i.customId||'').startsWith('detective:');
  if(!cmd&&!comp)return false;if(!i.guildId){await reply(i,{content:'❌ Chỉ hoạt động trong server.',flags:MessageFlags.Ephemeral});return true;}
  try{
    if(cmd){const s=i.options.getSubcommand();if(s==='case')return showCase(i);if(s==='profile')return profile(i,i.options.getUser('user')||i.user);return leaderboard(i,i.options.getInteger('limit')||10);}
    const p=String(i.customId).split(':');
    if(p[1]==='investigate')return investigateMenu(i);if(p[1]==='inspect')return inspect(i,i.values?.[0]);if(p[1]==='suspects')return suspects(i);if(p[1]==='questions')return questions(i,i.values?.[0]);if(p[1]==='questions_action')return interrogate(i,p[2],i.values?.[0]);if(p[1]==='timeline')return timeline(i);if(p[1]==='timeline_menu')return addTimeline(i,i.values?.[0]);if(p[1]==='submit')return submitModal(i);if(i.isModalSubmit()&&i.customId==='detective:submit_modal')return submitReport(i);
    return false;
  }catch(e){await reply(i,{content:'⚠️ Detective: '+e.message,flags:MessageFlags.Ephemeral});return true;}
}
function caseData(i){return game.getDailyCase(i.guildId);}
async function showCase(i){const c=caseData(i),inv=game.startInvestigation(i.user.id,c);const rows=[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('detective:investigate').setLabel('🔎 Điều tra').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('detective:suspects').setLabel('👥 Nghi phạm').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('detective:timeline').setLabel('🕐 Timeline').setStyle(ButtonStyle.Secondary)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('detective:submit').setLabel('⚖️ Nộp kết luận').setStyle(ButtonStyle.Success))];return i.reply({embeds:[new EmbedBuilder().setTitle('🕵️ DAILY CASE — '+c.title).setDescription(c.summary).addFields({name:'📊 Difficulty',value:'⭐'.repeat(c.difficulty),inline:true},{name:'🔎 Evidence',value:inv.evidenceFound.length+'/'+c.evidence.length,inline:true},{name:'👥 Suspects',value:c.suspects.map(s=>s.id+' — '+s.name).join('\n')}),],components:rows});}
async function investigateMenu(i){const c=caseData(i),inv=game.startInvestigation(i.user.id,c),targets=c.investigationTargets.filter(t=>!inv.inspectedTargets.includes(t.id));if(!targets.length)return reply(i,{content:'🔎 Bạn đã điều tra hết khu vực.',flags:MessageFlags.Ephemeral});const menu=new StringSelectMenuBuilder().setCustomId('detective:inspect').setPlaceholder('Chọn khu vực').addOptions(targets.map(t=>({label:t.label,value:t.id,description:'Tìm evidence'})));return i.reply({content:'🔎 Chọn khu vực để điều tra.',components:[new ActionRowBuilder().addComponents(menu)],flags:MessageFlags.Ephemeral});}
async function inspect(i,id){const c=caseData(i),r=game.investigate(i.user.id,c,id);return i.update({content:(r.evidence.tags.includes('red_herring')?'🟡 Red Herring':'🟢 Evidence')+'\n\n**'+r.evidence.name+'**\n'+r.evidence.description,components:[]});}
async function suspects(i){const c=caseData(i),menu=new StringSelectMenuBuilder().setCustomId('detective:questions').setPlaceholder('Chọn nghi phạm').addOptions(c.suspects.map(s=>({label:s.id+' — '+s.name,value:s.id,description:'Thẩm vấn'})));return i.reply({embeds:[new EmbedBuilder().setTitle('👥 Nghi phạm').setDescription(c.suspects.map(s=>s.id+' — '+s.name).join('\n'))],components:[new ActionRowBuilder().addComponents(menu)],flags:MessageFlags.Ephemeral});}
async function questions(i,id){const c=caseData(i),s=c.suspects.find(x=>x.id===id);if(!s)throw new Error('Không tìm thấy nghi phạm.');const menu=new StringSelectMenuBuilder().setCustomId('detective:questions_action:'+id).setPlaceholder('Chọn câu hỏi').addOptions([{label:'Hỏi về thời gian',value:'time',description:'Kiểm tra alibi'},{label:'Hỏi về món đồ',value:'object',description:'Kiểm tra khả năng tiếp cận'},{label:'Hỏi về người khác',value:'person',description:'Tìm mâu thuẫn'}]);return i.update({content:'👤 '+s.name+' — chọn câu hỏi',components:[new ActionRowBuilder().addComponents(menu)]});}
async function interrogate(i,id,a){const c=caseData(i),r=game.interrogate(i.user.id,c,id,a);return i.update({content:'👤 **Lời khai**\n\n'+r.response,components:[]});}
async function timeline(i){const c=caseData(i),menu=new StringSelectMenuBuilder().setCustomId('detective:timeline_menu').setPlaceholder('Chọn mốc').addOptions(c.timeline.map(t=>({label:t.time+' — '+t.id,value:t.id,description:t.text})));return i.reply({content:'🕐 Chọn mốc timeline.',components:[new ActionRowBuilder().addComponents(menu)],flags:MessageFlags.Ephemeral});}
async function addTimeline(i,id){const c=caseData(i);game.addTimelineEvent(i.user.id,c,id);return i.update({content:'🕐 Đã thêm '+id+' vào timeline.',components:[]});}
async function submitModal(i){const c=caseData(i),inv=game.startInvestigation(i.user.id,c);if(inv.evidenceFound.length<4||inv.suspectsInterrogated.length<1)return reply(i,{content:'🔒 Cần ít nhất 4 evidence và 1 lần thẩm vấn.',flags:MessageFlags.Ephemeral});const m=new ModalBuilder().setCustomId('detective:submit_modal').setTitle('⚖️ Final Detective Report');for(const [id,label,ph,max] of [['culprit','Thủ phạm','S1 hoặc tên',100],['motive','Động cơ','Bạn nghĩ vì sao?',500],['timeline','Timeline','T2,T3,T4',100],['reasoning','Lập luận','Giải thích kết luận',1000]])m.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(id).setLabel(label).setPlaceholder(ph).setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(max)));return i.showModal(m);}
async function submitReport(i){const c=caseData(i),r=game.submit(i.user.id,c,{culprit:i.fields.getTextInputValue('culprit'),motive:i.fields.getTextInputValue('motive'),timeline:i.fields.getTextInputValue('timeline').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean),reasoning:i.fields.getTextInputValue('reasoning')});return i.reply({embeds:[new EmbedBuilder().setTitle(r.result.culprit?'✅ Case Solved':'❌ Case Not Solved').setDescription('Thủ phạm: **'+c.solution.culpritName+'**\nĐiểm: **'+r.result.total+'**\nXP: **+'+r.result.xp+'**\nCulprit: '+(r.result.culprit?'✅':'❌')+' · Motive: '+(r.result.motive?'✅':'❌')+'\nTimeline: '+r.result.timelineScore+'/200 · Evidence: '+r.result.foundRequired+'/'+r.result.requiredEvidence+' · Reasoning: '+r.result.reasoningScore+'/500').addFields({name:'🪪 Profile',value:r.profile.rank+' · '+r.profile.xp+' XP · 🔥'+r.profile.streak})],flags:MessageFlags.Ephemeral});}
async function profile(i,u){const p=game.getProfile(u.id);return i.reply({embeds:[new EmbedBuilder().setTitle('🕵️ Detective Profile — '+u.username).addFields({name:'Rank',value:p.rank,inline:true},{name:'XP',value:String(p.xp),inline:true},{name:'Streak',value:'🔥 '+p.streak,inline:true},{name:'Cases',value:String(p.casesSolved),inline:true})],flags:MessageFlags.Ephemeral});}
async function leaderboard(i,n){const list=game.getLeaderboard(n);return i.reply({embeds:[new EmbedBuilder().setTitle('🏆 Detective Leaderboard').setDescription(list.length?list.map((p,x)=>'**'+(x+1)+'.** '+p.userId+' — '+p.xp+' XP · '+p.rank).join('\n'):'Chưa có Detective nào.')],flags:MessageFlags.Ephemeral});}
async function reply(i,p){return i.replied||i.deferred?i.followUp(p):i.reply(p);}
module.exports={commandsData,handleDetectiveInteraction,detectiveGame:game};